sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
- 10.13.0

cache:
  directories:
  - node_modules
  - bower_components
  - $HOME/.npm
  - $HOME/.cache

script:
  - npm test --silent

notifications:
  webhooks:
    - https://ab846f6b.ngrok.io/taskbook/travis/notifications
